version: '3.9'
services:
  go_app:
    build: ./
    command: ./main
    restart: always
    ports:
      - 8082:8081
    depends_on:
      db:
        condition: service_healthy
    environment:
      user: "postgres"
      password: "postgres"
      dbname: "postgres"
    networks:
      - app_network


  db:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 15s
      timeout: 15s
      retries: 10
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5439:5432
    volumes:
      - ./postgres:/var/lib/postgres/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - app_network