env: "local"
loglevel: -4
logformat: "text"
storage:
  host: "db"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
http_server:
  address: "0.0.0.0:8081"
  timeout: 4s
  idle_timeout: 60s
